---
api: 
  port: 4444                    # singleuser mode (api.py explicit launch)
databases: 
  mysql: 
    address: "127.0.0.1"
    port: 3360                  # NB! number only
    login: "api"
    password: "IamPermitt3d"
    database: "test_corp"
...
